### ISSUE TITLE
Contribute Parser to upstream

### ISSUE THREAD

**Issue by kenkangxgwe** [bryall/beancount-language-server#10]
Hi Brian, just found this project and noticed you are using tree-sitting to re-write the parser. Since beancount v3 is now under development. Have you considered to contribute some code upstream, so this language server can be a thin wrapper around the upstream python/c++ functions?

**Comment by bryall** [comment]
have not had time to look at v3 of beancount. Are they using tree-sitter? I will definitely look at v3 to make improvements to this project
